config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :chatrooms, param: :slug
  resources :messages

  resources :reports
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'
  get 'signin', to: 'main_pages#signin'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :jobs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  post 'jobs/archive/:id' => 'jobs#archive', :as => :archive
  post 'jobs/unarchive/:id' => 'jobs#unarchive', :as => :unarchive
  get 'archive' => 'jobs#archiveindex', :as => :archiveindex
  root 'jobs#index'
  
end

app/models/job.rb
class Job < ApplicationRecord
     
     before_save :default_values
     def default_values
          self.make ||= 'Not Started'
          self.qc ||= 'Not Started'
          self.fill ||= 'Not Started'
     end
     
     default_scope -> { order(created_at: :desc) }
     validates :no,  presence: true, length: { minimum: 5 }, uniqueness: true
     validates :desc,  presence: true, length: { maximum: 30 }
     validates :size,  presence: true
     validates :make,  length: { maximum: 50 }
     validates :qc,   length: { maximum: 50 }
     validates :fill,   length: { maximum: 50 }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :check_for_mobile
  def index
    if logged_in? then
      @jobs = Job.where(archived: false).paginate(page: params[:page])

      render '/jobs/index'
    else
      render '/sessions/new'
    end
  end
  
  def archiveindex
    if logged_in? then
      @jobs = Job.where(archived: true).paginate(page: params[:page])
      render '/jobs/index'
    else
      render '/sessions/new'
    end
  end
  
  def show
    @job = Job.find(params[:id])
  end
  
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = "Job successfully added!"
       redirect_to root_path
    else
      render 'new'
    end
  end
  
  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "Job updated"
       redirect_to root_path
    else
      render 'edit'
    end
  end
  
  def edit
    @job = Job.find(params[:id])
  end
  
  def destroy
    Job.find(params[:id]).destroy
    flash[:success] = "Job deleted"
     redirect_to root_path
  end
  
  def archive
    Job.find(params[:id]).update_attributes(:archived => true)
    flash[:success] = "Job successfully archived!"
    redirect_to root_path
  end
  
  def unarchive
    Job.find(params[:id]).update_attributes(:archived => false)
    flash[:success] = "Job successfully un-archived!"
    redirect_to root_path
  end
  
  private

    def job_params
      params.require(:job).permit(:no, :desc, :size,
                                   :make, :makecomment, :qc, :qccomment, :fill, :fillcomment)
    end
    
    
    
    
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <%= render 'shared/error_messages_job', object: @job %>
  <%= f.label "Job No" %>
  <%= f.number_field :no, class: 'form-control' %>

  <%= f.label "Description" %>
  <%= f.text_field :desc, class: 'form-control' %>

  <%= f.label :size %>
  <%= f.number_field :size, class: 'form-control' %>

  <% if  current_user.manufacturing? %>
    <%= f.label "Manufacturing" %>
    <%= f.select :make, options_for_select(['Not Started', 'Processing','Done'],@job.make) %>
    
    <%= f.label "Manufacturing Comment" %>
    <%= f.text_field :makecomment, class: 'form-control' %>
  <% end %>
  
  <% if current_user.qc? %>
    <%= f.label "Quality Control" %>
    <%= f.select :qc, options_for_select(['Not Started', 'Testing', 'Being Adjusted','Passed'],@job.qc) %>
    
    <%= f.label "QC Comment" %>
    <%= f.text_field :qccomment, class: 'form-control' %>
  <% end %>
  
  <% if current_user.filling? %>
    <%= f.label "Filling" %>
    <%= f.select :fill, options_for_select(['Not Started', 'Processing','Done'],@job.fill) %>
    
    <%= f.label "Filling Comment" %>
    <%= f.text_field :fillcomment, class: 'form-control' %>
  <% end %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/jobs/_job.html.erb
<tr>
  <td><%= link_to job.no, job %> </td>
  <td><%= job.desc %></td>  
  <td><%= job.size %></td>  
  <td <% if job.make == "Done" %> class = "done" <% end %>><%= job.make %><% if !job.makecomment.blank? %> - <% end %><%= job.makecomment %></td> 
  <td <% if job.qc == "Passed" %> class = "done" <% end %>><%= job.qc %><% if !job.qccomment.blank? %> - <% end %><%= job.qccomment %></td>  
  <td <% if job.fill == "Done" %> class = "done" <% end %>><%= job.fill %><% if !job.fillcomment.blank? %> - <% end %><%= job.fillcomment %></td>
  <td>
     <% if logged_in? %>
      <% if  current_user.manufacturing? || current_user.qc? || current_user.filling? %>
        <% if  !job.archived? %>
            <%= link_to "Update", edit_job_path(job) %>
           | <%= link_to("Archive", archive_path(job), method: :post)  %>
           | <%= link_to "Delete", job, method: :delete,
                                      data: { confirm: "You sure?" } %>
        <% end %>
        <% if  job.archived? %>
            <%= link_to "Update", edit_job_path(job) %>
           | <%= link_to("Un-Archive", unarchive_path(job), method: :post)  %>
           | <%= link_to "Delete", job, method: :delete,
                                      data: { confirm: "You sure?" } %>
        <% end %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/jobs/edit.html.erb
<% provide(:title, 'Edit Job') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Job</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/index.html.erb
<% provide(:title, 'All Jobs') %>
<script>
    $(document).ready(turbolinksSetInterval);
</script>
 
<% if request.fullpath.downcase().include? "archive" %>
  <h1>Archive</h1>
<% else %>
  <h1>Batch Status Report</h1>
<% end %>

<% if current_user && current_user.manufacturing? %>  
  <%= link_to "Add Job", new_job_path %>
<% end %>

<%= will_paginate %>


<table class = "table table-bordered">
  <tr class = "tableheader">
      <td><strong>Job No</strong></td>
      <td><strong>Description</strong></td>
      <td><strong>Size (L)</strong></td>
      <td><strong>Manufacturing</strong></td>
      <td><strong>Quality Control</strong></td>
      <td><strong>Filling<strong></td>
      <td></td>
  </tr>
  <%= render @jobs %>
</table>


<%= will_paginate %>
</br>

app/views/jobs/new.html.erb
<% provide(:title, 'Add Job') %>
<% provide(:button_text, 'Create Job') %>
<h1>Add Job</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/show.html.erb
<% provide(:title, @job.desc) %>
<script>
    $(document).ready(turbolinksSetInterval);
</script> 
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>
        <%= @job.no %>  <%= @job.desc %>
      </h3>
        <strong>Size: </strong><%= @job.size %> L</br></br>
        
        <strong>Manufacturing: </strong><%= @job.make %> &nbsp &nbsp
        <strong>Comment: </strong><%= @job.makecomment %></br>
        
        <strong>Quality Control: </strong><%= @job.qc %> &nbsp &nbsp
        <strong>Comment: </strong><%= @job.qccomment %></br>
        
        <strong>Filling: </strong><%= @job.fill %> &nbsp &nbsp
        <strong>Comment: </strong><%= @job.fillcomment %></br></br>
        
        <% if logged_in? %>
          <% if  current_user.manufacturing? || current_user.qc? || current_user.filling? %>
            <%= link_to "Update", edit_job_path(@job) %>
             | <%= link_to "Delete", @job, method: :delete,
                                data: { confirm: "You sure?" } %>
          <% end %>
        <% end %>
    </section>
  </aside>
</div>