config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :chatrooms, param: :slug
  resources :messages

  resources :reports
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'
  get 'signin', to: 'main_pages#signin'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :jobs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  post 'jobs/archive/:id' => 'jobs#archive', :as => :archive
  post 'jobs/unarchive/:id' => 'jobs#unarchive', :as => :unarchive
  get 'archive' => 'jobs#archiveindex', :as => :archiveindex
  root 'jobs#index'
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    has_many :chatrooms, through: :messages
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save   :downcase_email
    before_create :create_activation_digest
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
      has_secure_password
       validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

 # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
   # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
     self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
   # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
   # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
   
   # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private
   # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :create, :edit, :update]
  before_filter :check_for_mobile
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :admin, :qc, :manufacturing, :filling, :executive)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
     # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      if !current_user.admin?
       redirect_to(root_url)
      end
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
      if current_user && !current_user.admin?
        flash[:danger] = "You are not an administrator, you cannot change users."
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages_user', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  
 <% if current_user && current_user.admin? %>  
  <%= f.label :manufacturing %>
  <%= f.select :manufacturing, options_for_select([['No', false], ['Yes', true]],@user.manufacturing)%>
  
  <%= f.label "Quality Control" %>
  <%= f.select :qc, options_for_select([['No', false], ['Yes', true]],@user.qc)%>
  
  <%= f.label :filling %>
  <%= f.select :filling, options_for_select([['No', false], ['Yes', true]],@user.filling)%>
  
  
  <%= f.label :admin %>
  <%= f.select :admin, options_for_select([['No', false], ['Yes', true]],@user.admin)%>
  
   <%= f.label :executive %>
  <%= f.select :executive, options_for_select([['No', false], ['Yes', true]],@user.executive)%>
  <% end %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= link_to user.name, user %>
  </td>
  
  <td>
    <% if current_user.admin? %>
    <%= link_to "Edit", edit_user_path(user) %>
      |  <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<% if current_user && current_user.admin? %>
      <%= link_to "Add User", signup_path %>
<% end %>
<%= will_paginate %>

<table class = "table table-bordered table-striped">
  <tr class = "tableheader">
    <td>
      <strong>User</strong>
    </td>
    <td>
      <strong>Admin Options</strong>
    </td>
  </tr>
  
  <%= render @users %>
</table>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Add User') %>
<% provide(:button_text, 'Create my account') %>
<h1>Add User</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
        <% if @user.admin then %>
          (Administrator)
        <% end %>
      </h1>
      
        <%= @user.email %>
        <% if @user.executive then %>
          <p>Executive Reporting Access Granted</p>
        <% end %>
        <b>Departments:</b></br>
        
        <% if @user.manufacturing then %>
          Manufacturing </br>
        <% end %>
      
        <% if @user.qc then %>
          Quality Control </br>
        <% end %>
        
        <% if @user.filling then %>
          Filling </br>
        <% end %>
        
       
    </section>
  </aside>
</div>