config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :chatrooms, param: :slug
  resources :messages

  resources :reports
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'
  get 'signin', to: 'main_pages#signin'
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :jobs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  post 'jobs/archive/:id' => 'jobs#archive', :as => :archive
  post 'jobs/unarchive/:id' => 'jobs#unarchive', :as => :unarchive
  get 'archive' => 'jobs#archiveindex', :as => :archiveindex
  root 'jobs#index'
  
end

app/models/report.rb
class Report < ApplicationRecord
     attr_accessor :image
     default_scope -> { order(created_at: :desc) }
     validates :name,  presence: true, length: { minimum: 1 }
     validates :image,  presence: true
     mount_uploader :image, ImageUploader
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :check_for_mobile

  def index
    if logged_in? then
      if executive? then
        @reports = Report.paginate(page: params[:page])
        render '/reports/index'
      else
        flash[:warning] = "Reporting Access Denied"
        redirect_to jobs_url
      end
    else
      render '/sessions/new'
    end
  end
  
  def show
     @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def edit
    @report = Report.find(params[:id])
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      flash[:success] = "Report successfully added!"
       redirect_to reports_url
    else
      render 'new'
    end
  end

  def update
    @report = Report.find(params[:id])
    if @report.update_attributes(report_params)
      flash[:success] = "Report updated"
       redirect_to reports_url
    else
      render 'edit'
    end
  end

  def destroy
    Report.find(params[:id]).destroy
    flash[:success] = "Report deleted"
     redirect_to reports_url
  end

  private
    def report_params
      params.require(:report).permit(:name, :image)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <%= render 'shared/error_messages_report', object: @report %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.file_field :image, class: 'form-control' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/reports/_report.html.erb
<div class="col-sm-4">
    <h3 class = "text-center"><%= report.name%></h3>
    <div class="ih-item square colored effect6 from_top_and_bottom">
        <%= link_to report do %>
            <div class="img">
                <%= image_tag(report.image_url.to_s, alt: "Report Image", class: "thumbnail center-block") %>
            </div>
            <div class="info">
              <h3>Click to View</h3>
            </div>
        <% end %>
    </div>
    <p class = "text-center">
        <%= link_to 'Edit', edit_report_path(report) %> | 
        <%= link_to 'Delete', report, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
</div>

app/views/reports/edit.html.erb
<% provide(:title, 'Edit Report') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Report</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/reports/index.html.erb
<h1>Executive Reporting</h1>
<%= link_to 'Add Report', new_report_path %>
<div class="container">
    <%= render @reports %>
</div>

app/views/reports/new.html.erb
<% provide(:title, 'Add Report') %>
<% provide(:button_text, 'Create Report') %>
<h1>Add Report</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/reports/show.html.erb
<% provide(:title, @report.name) %>
<h1 class = "text-center"><%= @report.name %></h1>
<%= image_tag @report.image_url.to_s, class: "img-responsive center-block" %>
<p class = "text-center">
   <%= link_to 'Update', edit_report_path(@report) %> | 
   <%= link_to 'Delete', @report, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>